/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.AdminSessionLog;

public interface AdminSessionLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_admin_session_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_admin_session_log
     *
     * @mbggenerated
     */
    int insertSelective(AdminSessionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_admin_session_log
     *
     * @mbggenerated
     */
    AdminSessionLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_admin_session_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminSessionLog record);
}