/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.AdminSession;

public interface AdminSessionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_admin_session
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_admin_session
     *
     * @mbggenerated
     */
    int insertSelective(AdminSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_admin_session
     *
     * @mbggenerated
     */
    AdminSession selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_admin_session
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminSession record);
}