/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.FeedBackWithBLOBs;

public interface FeedBackDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feed_back
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feed_back
     *
     * @mbggenerated
     */
    int insertSelective(FeedBackWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feed_back
     *
     * @mbggenerated
     */
    FeedBackWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feed_back
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FeedBackWithBLOBs record);
}