/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.bean.FormatSubBean;
import com.honglinktech.zbgj.entity.FormatSub;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatSubDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_format_sub
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_format_sub
     *
     * @mbggenerated
     */
    int insertSelective(FormatSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_format_sub
     *
     * @mbggenerated
     */
    FormatSub selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_format_sub
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FormatSub record);

    /************************************************************************************************/
    /**
     *
     * @param shoppingId
     * @return
     */
    List<FormatSubBean> findFormatSubByShoppingId(@Param(value = "shoppingId")Integer shoppingId);
}