/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.Gactivity;

public interface GactivityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_activity
     *
     * @mbggenerated
     */
    int insertSelective(Gactivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_activity
     *
     * @mbggenerated
     */
    Gactivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Gactivity record);
}