/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.GoodsDis;

public interface GoodsDisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_dis
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_dis
     *
     * @mbggenerated
     */
    int insertSelective(GoodsDis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_dis
     *
     * @mbggenerated
     */
    GoodsDis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_dis
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsDis record);
}