/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.GoodsBrand;

public interface GoodsBrandDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_brand
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_brand
     *
     * @mbggenerated
     */
    int insertSelective(GoodsBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_brand
     *
     * @mbggenerated
     */
    GoodsBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_brand
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsBrand record);
}