/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.GoodsActivity;
import com.honglinktech.zbgj.entity.GoodsActivityKey;

public interface GoodsActivityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(GoodsActivityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_activity
     *
     * @mbggenerated
     */
    int insertSelective(GoodsActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_activity
     *
     * @mbggenerated
     */
    GoodsActivity selectByPrimaryKey(GoodsActivityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsActivity record);
}