/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.Module;

public interface ModuleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbggenerated
     */
    int insertSelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbggenerated
     */
    Module selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Module record);
}