/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.Payment;

public interface PaymentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbggenerated
     */
    int insertSelective(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbggenerated
     */
    Payment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Payment record);
}