/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.PostCompany;

public interface PostCompanyDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_company
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_company
     *
     * @mbggenerated
     */
    int insertSelective(PostCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_company
     *
     * @mbggenerated
     */
    PostCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PostCompany record);
}