/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.Security;

public interface SecurityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_security
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_security
     *
     * @mbggenerated
     */
    int insertSelective(Security record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_security
     *
     * @mbggenerated
     */
    Security selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_security
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Security record);
}