/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.ShoppingCartFormat;

public interface ShoppingCartFormatDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart_format
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart_format
     *
     * @mbggenerated
     */
    int insertSelective(ShoppingCartFormat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart_format
     *
     * @mbggenerated
     */
    ShoppingCartFormat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart_format
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShoppingCartFormat record);
}