/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.ShoppingCart;

public interface ShoppingCartDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart
     *
     * @mbggenerated
     */
    int insertSelective(ShoppingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart
     *
     * @mbggenerated
     */
    ShoppingCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShoppingCart record);
}