/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.SocietyNoteReward;

public interface SocietyNoteRewardDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note_reward
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note_reward
     *
     * @mbggenerated
     */
    int insertSelective(SocietyNoteReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note_reward
     *
     * @mbggenerated
     */
    SocietyNoteReward selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note_reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocietyNoteReward record);
}