/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.SocietyDisDisLike;
import com.honglinktech.zbgj.entity.SocietyDisDisLikeKey;

public interface SocietyDisDisLikeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis_dis_like
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SocietyDisDisLikeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis_dis_like
     *
     * @mbggenerated
     */
    int insertSelective(SocietyDisDisLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis_dis_like
     *
     * @mbggenerated
     */
    SocietyDisDisLike selectByPrimaryKey(SocietyDisDisLikeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis_dis_like
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocietyDisDisLike record);
}