/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.SocietySub;

public interface SocietySubDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_sub
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_sub
     *
     * @mbggenerated
     */
    int insertSelective(SocietySub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_sub
     *
     * @mbggenerated
     */
    SocietySub selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_sub
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocietySub record);
}