/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.SocietyNote;

public interface SocietyNoteDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note
     *
     * @mbggenerated
     */
    int insertSelective(SocietyNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note
     *
     * @mbggenerated
     */
    SocietyNote selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocietyNote record);
}