/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.SocietyNoteLike;
import com.honglinktech.zbgj.entity.SocietyNoteLikeKey;

public interface SocietyNoteLikeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note_like
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SocietyNoteLikeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note_like
     *
     * @mbggenerated
     */
    int insertSelective(SocietyNoteLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note_like
     *
     * @mbggenerated
     */
    SocietyNoteLike selectByPrimaryKey(SocietyNoteLikeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note_like
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocietyNoteLike record);
}