/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.SocietyType;

public interface SocietyTypeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_type
     *
     * @mbggenerated
     */
    int insertSelective(SocietyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_type
     *
     * @mbggenerated
     */
    SocietyType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocietyType record);
}