/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.SocietyDis;

public interface SocietyDisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis
     *
     * @mbggenerated
     */
    int insertSelective(SocietyDis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis
     *
     * @mbggenerated
     */
    SocietyDis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocietyDis record);
}