/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.SocietySubUser;
import com.honglinktech.zbgj.entity.SocietySubUserKey;

public interface SocietySubUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_sub_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SocietySubUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_sub_user
     *
     * @mbggenerated
     */
    int insertSelective(SocietySubUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_sub_user
     *
     * @mbggenerated
     */
    SocietySubUser selectByPrimaryKey(SocietySubUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_sub_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocietySubUser record);
}