/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.UserSession;

public interface UserSessionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_session
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_session
     *
     * @mbggenerated
     */
    int insertSelective(UserSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_session
     *
     * @mbggenerated
     */
    UserSession selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_session
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserSession record);
}