/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.UserMsg;

public interface UserMsgDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_msg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_msg
     *
     * @mbggenerated
     */
    int insertSelective(UserMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_msg
     *
     * @mbggenerated
     */
    UserMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_msg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserMsg record);
}