/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.UserSign;

public interface UserSignDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_sign
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_sign
     *
     * @mbggenerated
     */
    int insertSelective(UserSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_sign
     *
     * @mbggenerated
     */
    UserSign selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_sign
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserSign record);
}