/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.UserFriend;
import com.honglinktech.zbgj.entity.UserFriendKey;

public interface UserFriendDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_friend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UserFriendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_friend
     *
     * @mbggenerated
     */
    int insertSelective(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_friend
     *
     * @mbggenerated
     */
    UserFriend selectByPrimaryKey(UserFriendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_friend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserFriend record);
}