/**
 * @author ws
 * 2017-05-17 18:52:17
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.AdminRole;

public interface AdminRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_admin_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_admin_role
     *
     * @mbggenerated
     */
    int insertSelective(AdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_admin_role
     *
     * @mbggenerated
     */
    AdminRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_admin_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminRole record);
}