/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.ChangeLog;

import java.util.List;
import java.util.Map;

public interface ChangeLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_change_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_change_log
     *
     * @mbggenerated
     */
    int insertSelective(ChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_change_log
     *
     * @mbggenerated
     */
    ChangeLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_change_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChangeLog record);

    /*******************************************************************************************************************************/
    /**
     * 获取
     * @param whereMap
     * @return
     */
    List<ChangeLog> findByWhere(Map whereMap);
}