/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.bean.CouponUserBean;
import com.honglinktech.zbgj.entity.CouponUser;

import java.util.List;
import java.util.Map;

public interface CouponUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_user
     *
     * @mbggenerated
     */
    int insertSelective(CouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_user
     *
     * @mbggenerated
     */
    CouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CouponUser record);

    /***************************************************************************************************************/
    /**
     * 获取用户的可以优惠券数量
     * @param userId
     * @return
     */
	int findCouponCountByUser(Integer userId);
	
	/**
	 * 删除用户的优惠券
	 * @param userId
	 * @param couponId
	 * @return
	 */
	int deleteByUserIdAndCouponId(Integer userId, Integer couponId);
	
	/**
	 * 使用优惠券
	 * @param userId
	 * @param couponId
	 * @return
	 */
	int useCoupon(Integer userId, Integer couponId);

	/**
	 * console
	 * @param whereMap
	 * @return
	 */
    List<CouponUserBean> findUserCouponBeanByWhere(Map whereMap);

	/**
	 * console
	 * @param whereMap
	 * @return
	 */
	CouponUserBean findUserCouponBeanById(int id);

	/**
	 * console
	 * @param whereMap
	 * @return
	 */
	int findUserCouponBeanCountByWhere(Map whereMap);
}