/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.bean.ActivityBean;
import com.honglinktech.zbgj.entity.Gactivity;

import java.util.List;
import java.util.Map;

public interface GactivityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_activity
     *
     * @mbggenerated
     */
    int insertSelective(Gactivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_activity
     *
     * @mbggenerated
     */
    Gactivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Gactivity record);

    /**************************************************************************************/
    /**
     *
     * @param whereMap
     * @return
     */
    List<Gactivity> findByWhere(Map whereMap);

    /**
     *
     * @param whereMap
     * @return
     */
    int findCount(Map whereMap);

    /**
     *
     * @param goodsId
     * @return
     */
    List<ActivityBean> findAllByGoodsId(Integer goodsId);
}