/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.Gformat;

public interface GformatDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_format
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_format
     *
     * @mbggenerated
     */
    int insertSelective(Gformat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_format
     *
     * @mbggenerated
     */
    Gformat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_format
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Gformat record);
}