/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.GoodsType;

import java.util.List;
import java.util.Map;

public interface GoodsTypeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbggenerated
     */
    int insertSelective(GoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbggenerated
     */
    GoodsType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsType record);


    /******************************************************************************************************************************************************/
    /**
     * 查询所有商品类别
     * @return
     */
    List<GoodsType> findAll();

    /**
     * console 类别
     * @param whereMap
     * @return
     */
    List<GoodsType> findByWhere(Map whereMap);

    /**
     * console
     * @param whereMap
     * @return
     */
    int findCount(Map whereMap);
}