/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.GoodsTag;
import com.honglinktech.zbgj.entity.GoodsTagKey;

public interface GoodsTagDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(GoodsTagKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_tag
     *
     * @mbggenerated
     */
    int insertSelective(GoodsTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_tag
     *
     * @mbggenerated
     */
    GoodsTag selectByPrimaryKey(GoodsTagKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsTag record);
}