/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.GoodsFormat;
import com.honglinktech.zbgj.entity.GoodsFormatKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GoodsFormatDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_format
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(GoodsFormatKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_format
     *
     * @mbggenerated
     */
    int insertSelective(GoodsFormat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_format
     *
     * @mbggenerated
     */
    GoodsFormat selectByPrimaryKey(GoodsFormatKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_format
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsFormat record);

    /***************************************************************************/
    /**
     *
     * @param goodsFormats
     * @return
     */
    int saveBatch(List<GoodsFormat> goodsFormats);
    /**
     *
     * @param goodsId
     * @return
     */
    int deleteByGoodsId(@Param(value = "goodsId")Integer goodsId);
}