/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.bean.GoodsBean;
import com.honglinktech.zbgj.entity.Goods;
import com.honglinktech.zbgj.vo.GoodsVO;

import java.util.List;
import java.util.Map;

public interface GoodsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    Goods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Goods record);

    /*****************************************************************************************************/
    /**
     * App find by Id
     * @param id
     * @param userId
     * @return
     */
    GoodsBean appFindKeepById(int id, int userId);

    /**
     *
     * @param map
     * @return
     */
    List<GoodsBean> findGoodsSearchBeansByMap(Map map);

    /**
     * console.获取商品分页
     * @param whereMap
     * @return
     */
    List<GoodsVO> findGoodsVOPage(Map whereMap);
    /**
     * console.获取商品总数
     * @param whereMap
     * @return
     */
    long findGoodsCount(Map whereMap);
}