/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.bean.GoodsDisCountBean;
import com.honglinktech.zbgj.entity.GoodsDis;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface GoodsDisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_dis
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_dis
     *
     * @mbggenerated
     */
    int insertSelective(GoodsDis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_dis
     *
     * @mbggenerated
     */
    GoodsDis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_dis
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsDis record);

    /***********************************************************************************************************/
    /**
     * 查询商品评论统计
     * @param goodsId
     * @return
     */
    GoodsDisCountBean findGoodsDisCount(@Param(value = "goodsId")Integer goodsId);

    /**
     * 获取商品的评论
     * @param map
     * @return
     */
    List<GoodsDis> findByGoodsId(Map map);
}