/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.bean.GoodsTagBean;
import com.honglinktech.zbgj.entity.Gtag;

import java.util.List;
import java.util.Map;

public interface GtagDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_tag
     *
     * @mbggenerated
     */
    int insertSelective(Gtag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_tag
     *
     * @mbggenerated
     */
    Gtag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_g_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Gtag record);

    /*#############################################################################*/
    /**
     *
     * @param tagId
     * @return
     */
    List<GoodsTagBean> findAllByGoodsId(Integer tagId);

    /**
     *
     * @param whereMap
     * @return
     */
    List<Gtag> findByWhere(Map whereMap);

    /**
     *
     * @param whereMap
     * @return
     */
    int findCount(Map whereMap);
}