/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.Hint;
import com.honglinktech.zbgj.entity.HintKey;

public interface HintDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hint
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(HintKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hint
     *
     * @mbggenerated
     */
    int insertSelective(Hint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hint
     *
     * @mbggenerated
     */
    Hint selectByPrimaryKey(HintKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hint
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Hint record);
}