/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.bean.OrderBean;
import com.honglinktech.zbgj.bean.OrderSimpleBean;
import com.honglinktech.zbgj.entity.Order;

import java.util.List;
import java.util.Map;

public interface OrderDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Order record);

    /****************************************************************************************/
    /**
     * app 获取订单列表
     * @param map
     * @return
     */
    List<OrderBean> appFindOrderBeanList(Map map);

    /**
     * console 获取订单列表
     * @param whereMap
     * @return
     */
    List<OrderSimpleBean> findByWhere(Map whereMap);

    /**
     * console 获取数量
     * @param whereMap
     * @return
     */
    int findCount(Map whereMap);
}