/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.OrderActivity;

public interface OrderActivityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_activity
     *
     * @mbggenerated
     */
    int insertSelective(OrderActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_activity
     *
     * @mbggenerated
     */
    OrderActivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderActivity record);
}