/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.OrderItemFormat;

public interface OrderItemFormatDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_format
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_format
     *
     * @mbggenerated
     */
    int insertSelective(OrderItemFormat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_format
     *
     * @mbggenerated
     */
    OrderItemFormat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_format
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderItemFormat record);
}