/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.OrderItem;

import java.util.List;
import java.util.Map;

public interface OrderItemDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbggenerated
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbggenerated
     */
    OrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /************************************************************************************************************/
    /**
     * 批量插入
     * @param orderItems
     * @return
     */
    int saveBatch(List<OrderItem> orderItems);

    /**
     * 查询订单商品
     * @param map
     * @return
     */
    List<OrderItem> findByWhere(Map map);
}