/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.bean.PaymentBean;
import com.honglinktech.zbgj.entity.Payment;

import java.util.List;
import java.util.Map;

public interface PaymentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbggenerated
     */
    int insertSelective(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbggenerated
     */
    Payment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Payment record);

    /************************************************************************************/
    /**
     * app获取用户支付信息
     * @param map
     * @return
     */
    List<PaymentBean> findBeanByWhere(Map map);
}