/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.PostCompany;

import java.util.List;
import java.util.Map;

public interface PostCompanyDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_company
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_company
     *
     * @mbggenerated
     */
    int insertSelective(PostCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_company
     *
     * @mbggenerated
     */
    PostCompany findById(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PostCompany record);
    /*******************************************************************************************/
    /**
     * console
     * @param whereMap
     * @return
     */
    List<PostCompany> findPostCompanyByWhere(Map whereMap);

    /**
     * console
     * @param whereMap
     * @return
     */
    int findPostCompanyCountByWhere(Map whereMap);

}