/**
 * @author ws
 * 2017-05-17 18:52:17
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.RoleSecurity;

public interface RoleSecurityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_security
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_security
     *
     * @mbggenerated
     */
    int insertSelective(RoleSecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_security
     *
     * @mbggenerated
     */
    RoleSecurity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_security
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleSecurity record);
}