/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.ShoppingCartFormat;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface ShoppingCartFormatDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart_format
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart_format
     *
     * @mbggenerated
     */
    int insertSelective(ShoppingCartFormat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart_format
     *
     * @mbggenerated
     */
    ShoppingCartFormat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_cart_format
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShoppingCartFormat record);

    /**********************************************************************************************/
    /**
     *
     * @param map
     * @return
     */
    List<ShoppingCartFormat> findByWhere(Map map);

    /**
     * 批量插入
     * @param shoppingCartFormats
     * @return
     */
    int saveBatch(List<ShoppingCartFormat> shoppingCartFormats);

    /**
     * 删除
     * @param shoppingId
     * @return
     */
    int deleteByShoppingId(@Param(value = "shoppingId") Integer shoppingId);
}