/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.bean.SocietyTypeBean;
import com.honglinktech.zbgj.entity.SocietyType;

import java.util.List;
import java.util.Map;

public interface SocietyTypeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_type
     *
     * @mbggenerated
     */
    int insertSelective(SocietyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_type
     *
     * @mbggenerated
     */
    SocietyType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocietyType record);

    /************************************************************************************************/
    /**
     *
     * @param map
     * @return
     */
    List<SocietyTypeBean> findBeanByWhere(Map map);

    /**
     * console
     * @param map
     * @return
     */
    List<SocietyType> findByWhere(Map map);

    /**
     * console
     * @param map
     * @return
     */
    int findCountByWhere(Map map);
}