/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.bean.SocietyDisDisBean;
import com.honglinktech.zbgj.entity.SocietyDisDis;

import java.util.List;

public interface SocietyDisDisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis_dis
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis_dis
     *
     * @mbggenerated
     */
    int insertSelective(SocietyDisDis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis_dis
     *
     * @mbggenerated
     */
    SocietyDisDis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis_dis
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocietyDisDis record);

    /*******************************************************************************/
    /**
     * societyDisId
     * @param societyDisId
     * @return
     */
    List<SocietyDisDisBean> findSocietyDisDis(Integer societyDisId);
}