/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.bean.SocietyNoteRewardBean;
import com.honglinktech.zbgj.entity.SocietyNoteReward;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface SocietyNoteRewardDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note_reward
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note_reward
     *
     * @mbggenerated
     */
    int insertSelective(SocietyNoteReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note_reward
     *
     * @mbggenerated
     */
    SocietyNoteReward selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note_reward
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocietyNoteReward record);

    /*************************************************************************************************************************/
    /**
     *
     * @param map
     * @return
     */
    List<SocietyNoteRewardBean> findSocietyNoteRewardByWhere(Map map);

    /**
     *
     * @param socNoteId
     * @return
     */
    int findSocietyNoteRewardCount(@Param(value = "socNoteId")Integer socNoteId);
}