/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.SocietyDisLike;
import com.honglinktech.zbgj.entity.SocietyDisLikeKey;

public interface SocietyDisLikeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis_like
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SocietyDisLikeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis_like
     *
     * @mbggenerated
     */
    int insertSelective(SocietyDisLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis_like
     *
     * @mbggenerated
     */
    SocietyDisLike selectByPrimaryKey(SocietyDisLikeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_dis_like
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocietyDisLike record);
}