/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.SocietySubTypeUser;
import com.honglinktech.zbgj.entity.SocietySubUserKey;

public interface SocietySubTypeUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_sub_type_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SocietySubUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_sub_type_user
     *
     * @mbggenerated
     */
    int insertSelective(SocietySubTypeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_sub_type_user
     *
     * @mbggenerated
     */
    SocietySubTypeUser selectByPrimaryKey(SocietySubUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_sub_type_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocietySubTypeUser record);
}