/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.bean.SocietyNoteBean;
import com.honglinktech.zbgj.entity.SocietyNote;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface SocietyNoteDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note
     *
     * @mbggenerated
     */
    int insertSelective(SocietyNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note
     *
     * @mbggenerated
     */
    SocietyNote selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_society_note
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocietyNote record);

    /*********************************************************************/
    /**
     * 查询详情
     * @param userId
     * @param id
     * @param socSubInfo
     * @return
     */
    SocietyNoteBean findSocietyNoteById(@Param(value = "userId")Integer userId, @Param(value = "id")Integer id, @Param(value = "socSubInfo")Boolean socSubInfo);

    /**
     * 查询列表
     * @param map
     * @return
     */
    List<SocietyNoteBean> findSocietyNotes(Map map);

    /**
     *
     * @param socNoteId
     * @param like
     * @return
     */
    int updateSocNoteLikeNum(Integer socNoteId, Boolean like);
}