/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.SystemMsg;

public interface SystemMsgDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_msg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_msg
     *
     * @mbggenerated
     */
    int insertSelective(SystemMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_msg
     *
     * @mbggenerated
     */
    SystemMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_msg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemMsg record);
}