/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.SystemConfig;

import java.util.List;

public interface SystemConfigDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbggenerated
     */
    int insertSelective(SystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbggenerated
     */
    SystemConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemConfig record);


    /********************************************************************/
    /**
     *
     * @return
     */
    List<SystemConfig> findAll();
}