/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.UserRanking;

public interface UserRankingDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ranking
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ranking
     *
     * @mbggenerated
     */
    int insertSelective(UserRanking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ranking
     *
     * @mbggenerated
     */
    UserRanking selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ranking
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRanking record);
}