/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.UserRec;

public interface UserRecDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_rec
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_rec
     *
     * @mbggenerated
     */
    int insertSelective(UserRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_rec
     *
     * @mbggenerated
     */
    UserRec selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_rec
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRec record);
}