/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.UserSocMsg;

public interface UserSocMsgDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_soc_msg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_soc_msg
     *
     * @mbggenerated
     */
    int insertSelective(UserSocMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_soc_msg
     *
     * @mbggenerated
     */
    UserSocMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_soc_msg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserSocMsg record);
}