/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.bean.UserBean;
import com.honglinktech.zbgj.common.Response;
import com.honglinktech.zbgj.entity.User;
import com.honglinktech.zbgj.vo.UserVO;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface UserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /*******************************************************************************************************************************/
    /**
     * 获取被关注数最多的用户
     * @param userId
     * @param start
     * @param rows
     * @return
     */
    List<User> findAtteUserByNum(@Param(value = "userId")Integer userId, @Param(value = "start")int start, @Param(value = "rows")int rows);
    /**
     *
     * @param userId
     * @param start
     * @param rows
     * @return
     */
    List<User> findFriendUserByNum(@Param(value = "userId")Integer userId, @Param(value = "start")int start, @Param(value = "rows")int rows);

    /**
     * login
     * @param account
     * @param password
     * @return
     */
    User login(String account, String password);


    /**
     * console
     * @param whereMap
     * @return
     */
    List<User> findList(Map<String, Object> whereMap);

    /**
     * consle
     * @param whereMap
     * @return
     */
    long findCount(Map<String, Object> whereMap);

    /**
     * 通过微信ID获取用户信息
     * @param openId
     * @return
     */
    User findByOpenId(String openId);
}