/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.UserKeep;

import java.util.List;
import java.util.Map;

public interface UserKeepDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_keep
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_keep
     *
     * @mbggenerated
     */
    int insertSelective(UserKeep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_keep
     *
     * @mbggenerated
     */
    UserKeep selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_keep
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserKeep record);

    /**********************************************************************************************************/
    /**
     * 查询
     * @param where
     * @return
     */
    List<UserKeep> findByWhere(Map where);

    /**
     * 删除收藏
     * @param uk
     * @return
     */
    int deleteKeep(UserKeep uk);
}