/**
 * @author ws
 * 2017-04-20 22:04:20
 */
package com.honglinktech.zbgj.dao;

import com.honglinktech.zbgj.entity.UserAtte;
import com.honglinktech.zbgj.entity.UserAtteKey;

public interface UserAtteDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_atte
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UserAtteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_atte
     *
     * @mbggenerated
     */
    int insertSelective(UserAtte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_atte
     *
     * @mbggenerated
     */
    UserAtte selectByPrimaryKey(UserAtteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_atte
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserAtte record);
}